force-app/main/default/objects/Command__c/Command__c.object-meta.xml
<CustomObject>
    <label>Command</label>
    <nameField>
        <displayFormat>CMD-{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Commands</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Command__c/fields/Operation__c.field-meta.xml
<CustomField>
    <fullName>Operation__c</fullName>
    <label>Operation</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Create</fullName>
            </value>
            <value>
                <fullName>Update</fullName>
            </value>
            <value>
                <fullName>Delete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Command__c/fields/RecordId__c.field-meta.xml
<CustomField>
    <fullName>RecordId__c</fullName>
    <description>Holds the related record&apos;s ID. This is just a text field to allow for polymorphism.</description>
    <inlineHelpText>Holds the related record&apos;s ID. This is just a text field to allow for polymorphism.</inlineHelpText>
    <label>Record ID</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Command__c/fields/UpdatedFieldsJSON__c.field-meta.xml
<CustomField>
    <fullName>UpdatedFieldsJSON__c</fullName>
    <description>A JSON of the updated field values by field name. Only relevant for create and update operations.</description>
    <inlineHelpText>A JSON of the updated field values by field name. Only relevant for create and update operations.</inlineHelpText>
    <label>Updated Fields (JSON)</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/TriggeredEvent__e/TriggeredEvent__e.object-meta.xml
<CustomObject>
    <description>A simple Platform Event used to initiate processing from a trigger.</description>
    <label>Triggered Event</label>
    <pluralLabel>Triggered Events</pluralLabel>
</CustomObject>

force-app/main/default/objects/TriggeredEvent__e/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Names the type of processing associated with the Platform Event.</description>
    <label>Type</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CaseHandler.cls
/*
 * MIT License. See the associated LICENSE file.
 * 
 * Copyright sirephil (c) 2023.
 */

/**
 * The handler for DML against the Case object.
 */
public without sharing class CaseHandler {
    /**
     * The transaction-wide tracking as to whether or not a "triggered event" has already been published by any
     * instances of this type of handler.
     */
    private static Boolean published = false;

    /**
     * Provides access to the singleton case handler.
     *
     * @return the singleton instance for this case handler. Will not be null.
     */
    public static CaseHandler getInstance() {
        return (CaseHandler) SingletonFactory.get(CaseHandler.class);
    }

    /**
     * Allows the Cases to be processed.
     *
     * @param oldCases the Case instances, in their previous state, to be processed. May be null.
     * @param newCases the Case instances, in their updated state, to be processed. May be null.
     */
    public void process(Case[] oldCases, Case[] newCases) {
        List<Command__c> commands = new List<Command__c>();

        if (newCases == null) {
            // The cases are being deleted so create appropriate commands
            for (Case oldCase : oldCases) {
                commands.add(new Command__c(
                        RecordId__c = oldCase.Id,
                        Operation__c = 'Delete'));
            }
        } else {
            // These fields are not of interest in the data sent to the callout
            Set<String> excludedFields = new Set<String> {
                    'SystemModstamp',
                    'CreatedById',
                    'CreatedDate',
                    'LastModifiedDate',
                    'LastModifiedById'
            };
            Map<String, SObjectField> fields = SObjectType.Case.fields.getMap();

            if (oldCases == null) {
                // The new cases are being added so create appropriate commands
                for (Case newCase : newCases) {
                    Map<String, String> changedFields = new Map<String, String>();

                    // Check each field in turn
                    for (SObjectField field : fields.values()) {
                        if (!excludedFields.contains(field.getDescribe().name) && newCase.get(field) != null) {
                            // The field wasn't an excluded one and has a value
                            changedFields.put(field.getDescribe().name, newCase.get(field).toString());
                        }
                    }

                    commands.add(new Command__c(
                            RecordId__c = newCase.Id,
                            Operation__c = 'Create',
                            UpdatedFieldsJSON__c = JSON.serialize(changedFields)));
                }
            } else if (newCases != null && oldCases != null) {
                // Cases are being updated, so generate commands if they are required, based on the changes made
                Map<Id, Case> oldCasesById = new Map<Id, Case>(oldCases);

                // Check all the cases to see if any of them have actual field value changes
                for (Case newCase : newCases) {
                    Case oldCase = oldCasesById.get(newCase.Id);
                    Map<String, String> changedFields = new Map<String, String>();

                    // Check each field in turn
                    for (SObjectField field : fields.values()) {
                        if (!excludedFields.contains(field.getDescribe().name) && newCase.get(field) != oldCase.get(field)) {
                            // The field wasn't an excluded one and has a value change
                            changedFields.put(field.getDescribe().name, newCase.get(field).toString());
                        }
                    }

                    if (!changedFields.isEmpty()) {
                        // There's some useful change information available so generate a command
                        commands.add(new Command__c(
                                RecordId__c = newCase.Id,
                                Operation__c = 'Update',
                                UpdatedFieldsJSON__c = JSON.serialize(changedFields)));
                    }
                }
            }
        }

        // Insert the commands (if there are any)
        insert commands;

        // Make sure to start processing of the command(s) that were added, in a separate transaction, using
        // the command processor
        if (!published && !commands.isEmpty()) {
            EventBus.publish(new TriggeredEvent__e(Type__c = CommandProcessor.class.getName()));

            // This transaction-wide tracking update ensures that we only publish at most one
            // triggered event in a given transaction for this type of processing.
            published = true;
        }
    }
}