force-app/main/default/objects/Command__c/Command__c.object-meta.xml
<CustomObject>
    <label>Command</label>
    <nameField>
        <displayFormat>CMD-{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Commands</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Command__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>The command&apos;s status.</description>
    <inlineHelpText>The command&apos;s status.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Sending</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TriggeredEvent__e/TriggeredEvent__e.object-meta.xml
<CustomObject>
    <description>A simple Platform Event used to initiate processing from a trigger.</description>
    <label>Triggered Event</label>
    <pluralLabel>Triggered Events</pluralLabel>
</CustomObject>

force-app/main/default/objects/TriggeredEvent__e/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Names the type of processing associated with the Platform Event.</description>
    <label>Type</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CommandSender.cls
/*
 * MIT License. See the associated LICENSE file.
 *
 * Copyright sirephil (c) 2023.
 */

/**
 * This queueable is responsible for sending callouts to some fictional end point. This code doesn't actually do
 * the callout but does everything else that would be required.
 */
public with sharing class CommandSender implements Queueable, Database.AllowsCallouts {
    /**
     * The IDs of the commands that must be sent.
     */
    private final Set<Id> commandIds;

    /**
     * Initializes the new instance using the given parameters.
     *
     * @param commandIds the IDs of the commands that must be sent.
     */
    public CommandSender(Set<Id> commandIds) {
        Assert.isTrue(commandIds.size() <= 100, 'A maximum of 100 commands can be sent in one go');

        this.commandIds = commandIds;
    }

    // apexdoc inherited
    public void execute(QueueableContext context) {
        List<Command__c> updates = new List<Command__c>();

        // Firstly, get those callouts made for the commands the sender was given on construction
        doCallouts();

        // Update these sent commands to indicate they are now complete
        for (Id commandId : commandIds) {
            updates.add(new Command__c(
                    Id = commandId,
                    Status__c = 'Complete'));
        }

        update updates;

        // Ensure that any pending commands will be processed by generating a Platform Event to nudge this
        // processing
        if (new CommandProcessor().needsMoreProcessing()) {
            String processor = CommandProcessor.class.getName();

            EventBus.publish(new TriggeredEvent__e(Type__c = processor));
        }
    }

    /**
     * Perform the callouts using the commands this sender was given on construction.
     */
    private void doCallouts() {
        // TODO this is left for implementing as required
    }
}